---
title: "Gavrila_reactome_summary"
author: "Henrique Camara"
date: '2024-06-13'
output: html_document
---

```{r setup, include=FALSE}
# Set global chunk options for knitr
knitr::opts_chunk$set(echo = TRUE)

# Load necessary libraries
library(ggplot2)
library(tidyverse)
library(stringr)
library(openxlsx)

# Define a custom theme
custom_theme <- theme_bw() + theme(
  axis.title = element_text(size = 14),
  axis.text = element_text(size = 12),
  plot.title = element_text(size = 16, face = "bold"),
  legend.title = element_text(size = 14),
  legend.text = element_text(size = 12),
  strip.text = element_text(size = 14)
)

# Apply the theme globally
theme_set(custom_theme)


# Alternative text wrapping function
wrap_text <- function(x, width) {
  str_wrap(x, width = width)
}

# Function to format text: uppercase and replace special characters
format_text <- function(text) {
  # Convert text to uppercase
  text_upper <- str_to_upper(text)

  # Replace special characters with underscores
  text_clean <- str_replace_all(text_upper, "[^A-Z0-9]", "_")

  # Remove potential double underscores
  text_clean <- str_replace_all(text_clean, "__+", "_")

  return(text_clean)
}

# Function to convert to sentence case
sentence_case <- function(text) {
  # Convert the first letter to uppercase and the rest to lowercase
  paste0(toupper(substr(text, 1, 1)), tolower(substr(text, 2, nchar(text))))
}

# Define date prefix
date_prefix <- format(Sys.Date(), "%Y-%m-%d")
```

# --- Reading BMI adjusted
```{r}
path_list <- list()
# Define a function to format text (ensure this is defined elsewhere in your code)
format_text <- function(text) {
  # Convert text to uppercase
  text_upper <- str_to_upper(text)
  
  # Replace special characters with underscores
  text_clean <- str_replace_all(text_upper, "[^A-Z0-9]", "_")
  text_clean <- gsub("__", "_", text_clean)  # Replace potential double underscores created
  
  return(text_clean)
}

# Path to the Excel file
path <- "../data/neck_fat_rnaseq_adj_covars/reactome_gsea.xlsx"

sheet_names <- getSheetNames(path)

sheets <- lapply(sheet_names, function(sheet) {
  df <- read.xlsx(path, sheet = sheet)
  df$Cluster <- sheet
  df$Description <- format_text(df$Description)
  return(df)
})

read.xlsx(path)
names(sheets) <- sheet_names
BMI_temp <- bind_rows(sheets)
path_list[["BMI_temp"]] <- BMI_temp
rm(BMI_temp)
```

```{r}
# Load only the data form the covariate corrected files
covar_data <- path_list[["BMI_temp"]]

# Replace the pathway name that is too big
covar_data <-
  covar_data %>% mutate(Description = case_when(
    Description == "RESPIRATORY_ELECTRON_TRANSPORT_ATP_SYNTHESIS_BY_CHEMIOSMOTIC_COUPLING_AND_HEAT_PRODUCTION_BY_UNCOUPLING_PROTEINS_" ~ "CHEMIOSMOTIC_COUPLING_AND_HEAT_PRODUCTION_BY_UNCOUPLING_PROTEINS",
    TRUE ~ Description
  ))
```

```{r}
# Format the data to have the covariate independent of tissue location
covar_data <- covar_data %>%
  mutate( # Extract text before the dot
    "Tissue" = str_extract(Cluster, "^[^.]+"),
    # ^[^.]+ means match the beginning of the string (^) and then match one or more characters that are not a dot ([^.]+)
    # Extract text after the dot
    "Covariate" = str_extract(Cluster, "(?<=\\.)[^.]+")
    # (?<=\\.) means match only the text that follows a dot (lookbehind assertion), and [^.]+ matches one or more characters that are not a dot
  ) %>%
  mutate(
    Tissue = case_when(
      Tissue == "SC" ~ "SubQ",
      TRUE ~ Tissue # Keep existing value if not matched
    )
  ) %>%
  filter(Tissue != "Deep_and_SC")

# Create a data frame with all possible combinations of Description, Tissue and Covariate
all_combinations <- expand.grid(
  Description = unique(covar_data$Description),
  Tissue = unique(covar_data$Tissue),
  Covariate = unique(covar_data$Covariate),
  stringsAsFactors = FALSE
)

# Merge with the original data, replacing missing values
f.covar_data <- all_combinations %>%
  left_join(covar_data, by = c("Description", "Tissue", "Covariate")) %>%
  mutate(
    NES = ifelse(is.na(NES), 0, NES),
    p.adjust = ifelse(is.na(p.adjust), 1, p.adjust)
  )

# Get unique covariates and exclude the ones combining DEEP and SC for the correlation
covars <- f.covar_data %>%
  filter(Tissue != "Deep_and_SC") %>%
  pull(Covariate) %>%
  unique()
```

# Plot Thermogenic Paths in All Covariates Side-by-side - Figure 4
```{r}
# Assign thermogenic pathways to a vector
thermo_paths <- c(
  # These are bioenergetics/thermogenesis-related pathways
  "CHEMIOSMOTIC_COUPLING_AND_HEAT_PRODUCTION_BY_UNCOUPLING_PROTEINS", "THE_CITRIC_ACID_TCA_CYCLE_AND_RESPIRATORY_ELECTRON_TRANSPORT", "RESPIRATORY_ELECTRON_TRANSPORT_ATP_SYNTHESIS_BY_CHEMIOSMOTIC_COUPLING_AND_HEAT_PRODUCTION_BY_UNCOUPLING_PROTEINS", "RESPIRATORY_ELECTRON_TRANSPORT", "FATTY_ACID_METABOLISM", "PYRUVATE_METABOLISM_AND_CITRIC_ACID_TCA_CYCLE", "INTEGRATION_OF_ENERGY_METABOLISM", "REGULATION_OF_LIPID_METABOLISM_BY_PPARALPHA", "KETONE_BODY_METABOLISM", "REGULATION_OF_GLYCOLYSIS_BY_FRUCTOSE_2_6_BISPHOSPHATE_METABOLISM", "INTRACELLULAR_METABOLISM_OF_FATTY_ACIDS_REGULATES_INSULIN_SECRETION",

  # These are mitochondrial related pathways
  "MITOCHONDRIAL_TRANSLATION", "MITOCHONDRIAL_TRANSLATION_ELONGATION", "MITOCHONDRIAL_TRANSLATION_INITIATION", "MITOCHONDRIAL_TRANSLATION_TERMINATION", "MITOCHONDRIAL_PROTEIN_IMPORT", "MITOCHONDRIAL_BIOGENESIS", "MITOCHONDRIAL_FATTY_ACID_BETA_OXIDATION", "BIOLOGICAL_OXIDATIONS", "MITOCHONDRIAL_FATTY_ACID_BETA_OXIDATION_OF_UNSATURATED_FATTY_ACIDS", "MITOCHONDRIAL_UNCOUPLING",

  # This is creatine metabolism related
  "CREATINE_METABOLISM"
)
```

```{r}
# Define width and height of plots
w <- 12
h <- 5

# Create output directory if it does not exist
output_dir <- paste0("./figures/Paper_figures/DotPlot/DEEP_SC_Thermogenic_pathways/ALL")
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

# Filter for the thermogenic pathways
plot.data <- f.covar_data %>% filter(Description %in% c(thermo_paths)) 

plot.data <- plot.data %>%
  filter(!Covariate %in% c("T4_per_mcg_protein", "T3_per_mcg_protein")) %>%
  mutate(Covariate = case_when(
    Covariate == "FreeT4" ~ "Serum Free T4",
    Covariate == "T4_per_mcg_protein" ~ "T4/μg of protein",
    Covariate == "T3_per_mcg_protein" ~ "T3/μg of protein",
    Covariate == "T4_per_mg_tissue" ~ "T4/mg of tissue",
    Covariate == "T3_per_mg_tissue" ~ "T3/mg of tissue",
    Covariate == "FreeT3" ~ "Serum Free T3",
    Covariate == "HYPERvsHYPO" ~ "Hyperthyroidism vs Hypothyroidism",
    Covariate == "TSH" ~ "Serum TSH"
  ))

# Order with positives first
pos_nes <- plot.data %>%
  filter(NES >= 0) %>%
  arrange(p.adjust)
neg_nes <- plot.data %>%
  filter(NES < 0) %>%
  arrange(desc(p.adjust))

plot.data <- bind_rows(pos_nes, neg_nes)

# Calculate min and max for -log10(p.adjust)
min_neg_log_padj <- min(-log10(plot.data$p.adjust))
max_neg_log_padj <- max(-log10(plot.data$p.adjust))


# Order Covariate and format text
desired_order <- c("Serum TSH", "Serum Free T4", "Serum Free T3", "T4/mg of tissue", "T3/mg of tissue", "Hyperthyroidism vs Hypothyroidism")
plot.data <- plot.data %>% filter(Covariate %in% desired_order) #Keep only original correlations
plot.data$Covariate <- factor(plot.data$Covariate, levels = desired_order)
plot.data$Description <- gsub("_", " ", plot.data$Description)

# Create plot ordered by NES
g <- ggplot(plot.data, aes(Tissue, Description)) +
  geom_count(aes(size = -log10(p.adjust), fill = NES), shape = 21, stroke = 0.5) +
  facet_grid(. ~ Covariate,
    scales = "free_x", space = "free_x",
    labeller = labeller(Covariate = function(x) str_wrap(x, width = 15))
  ) + 
  geom_text(
    data = plot.data %>% filter(p.adjust < 0.05),
    aes(label = "*"),
    color = "black",
    size = 6,
    vjust = 0
  ) + 
  scale_y_discrete(labels = function(x) str_wrap(x, width = 10)) + # Wrap y-axis labels
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  scale_y_discrete(limits = rev(unique(plot.data$Description))) +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5, size = 14), # Increase x-axis text size
    axis.text.y = element_text(size = 14), # Increase y-axis text size
    axis.title.x = element_blank(), # Remove x-axis title
    axis.title.y = element_blank(), # Remove y-axis title
    plot.title = element_text(size = 20, face = "bold", hjust = 0.5), # Center and increase title size
    legend.text = element_text(size = 12), # Increase legend text size
    legend.title = element_text(size = 14), # Increase legend title size
    strip.text.x = element_text(size = 12, face = "bold", margin = margin(b = 10, t = 10)) # Style for facet labels with spacing
  ) +
  labs(title = "Thermogenesis-related pathways")


# Save plot as PNG with date prefix
ggsave(
  filename = file.path("../output/4 - Figures and Analysis/figures/Figure_4_thermogenesis_all_covars_dotplot.png"),
  plot = g, device = "png", width = 20, height = 15, units = "in", dpi = 600, create.dir = T
)

# Save plot as TIFF with date prefix
ggsave(
  filename = file.path("../output/4 - Figures and Analysis/figures/Figure_4_thermogenesis_all_covars_dotplot.tiff"),
  plot = g, device = "tiff", width = 20, height = 15, units = "in", dpi = 600, create.dir = T
)

pdf(file.path("../output/4 - Figures and Analysis/figures/Figure_4_thermogenesis_all_covars_dotplot.pdf"), width = 20, height = 15)
# Print plot to PDF
print(g)
# Close the PDF device
dev.off()
```


# Plotting the top 5 pathways - Figures 5A and 6A
```{r}
# Create vector to fave the figures
covars <- unique(f.covar_data$Covariate)
fig_number <-  c("6", "5",rep("N", length(covars) -2))
fig_number <- setNames(fig_number, c("FreeT3", "FreeT4", setdiff(covars, c("FreeT3", "FreeT4"))))
```

```{r}
# Define width and height of plots
w <- 15
h <- 5

# Define top X
n_top <- 5

# Create output directory if it does not exist
output_dir <- paste0("./figures/Paper_figures/DotPlot/top_", n_top)
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

# Loop through each covariate and generate plots
for (covar in covars) {
  plot.data <- f.covar_data %>% filter(Covariate == covar)
  # plot.data$Description <- sentence_case(plot.data$Description)

  # Order with positives first
  pos_nes <- plot.data %>%
    filter(NES >= 0) %>%
    group_by(Tissue) %>%
    arrange(p.adjust) %>%
    slice_head(n = n_top)
  neg_nes <- plot.data %>%
    filter(NES < 0) %>%
    group_by(Tissue) %>%
    arrange(desc(p.adjust)) %>%
    slice_tail(n = n_top)

  plot.data <- bind_rows(pos_nes, neg_nes)

  # Calculate min and max for -log10(p.adjust)
  min_neg_log_padj <- min(-log10(plot.data$p.adjust))
  max_neg_log_padj <- max(-log10(plot.data$p.adjust))

  # Create plot ordered by NES
  g <- ggplot(plot.data, aes(Tissue, Description)) +
    geom_count(aes(size = -log10(p.adjust), fill = NES), shape = 21, color = "black", stroke = 0.5) +
      # Add asterisks for p.adjust < 0.05
  geom_text(
    data = plot.data %>% filter(p.adjust < 0.05),
    aes(label = "*"),
    color = "black",
    size = 6,
    vjust = 0.5,
    hjust = 1.75
  ) + # Adjust the position of the asterisk
    scale_y_discrete(labels = function(x) wrap_text(x, width = 10)) +
    scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
    scale_y_discrete(limits = rev(unique(plot.data$Description))) +
    theme(
      axis.text.x = element_text(angle = 0, hjust = 0.5, size = 14), # Increase x-axis text size
      axis.text.y = element_text(size = 14), # Increase y-axis text size
      axis.title.x = element_blank(), # Remove x-axis title
      axis.title.y = element_blank(), # Remove y-axis title
      plot.title = element_text(size = 16, face = "bold"), # Increase title size and make it bold
      legend.text = element_text(size = 12), # Increase legend text size
      legend.title = element_text(size = 14) # Increase legend title size
    ) +
    labs(title = paste0(covar, "\n", "Top ", n_top, " correlated pathways"))

  # Save plot as PNG with date prefix
  ggsave(
    filename = file.path("../output/5_6 - Figures and Analysis/figures",  paste0(date_prefix, "_", "Figure_", fig_number[covar], "A_",  covar, "_top_", n_top, "_pathways.png")),
    plot = g, device = "png", width = w, height = h, units = "in", dpi = 600, create.dir = T
  )
  
    # Save plot as TIFF with date prefix
  ggsave(
    filename = file.path("../output/5_6 - Figures and Analysis/figures",  paste0(date_prefix, "_","Figure_", fig_number[covar], "A_",  covar, "_top_", n_top, "_pathways.tiff")),
    plot = g, device = "tiff", width = w, height = h, units = "in", dpi = 600, create.dir = T
  )
  # Save PDF
  pdf(file.path("../output/5_6 - Figures and Analysis/figures",  paste0(date_prefix, "_","Figure_", fig_number[covar], "A_",  covar, "_top_", n_top, "_pathways.pdf")), width = w, height = h)
  print(g)
  dev.off()
}
```

# Plot Thermogenic Pathways - Figure 5B and 6B
```{r}
# Define width and height of plots
w <- 12
h <- 5

# Create output directory if it does not exist
output_dir <- paste0("./figures/Paper_figures/DotPlot/DEEP_SC_Thermogenic_pathways")
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

# Loop through each covariate and generate plots
for (covar in covars) {
  plot.data <- f.covar_data %>% filter(
    Covariate == covar,
    Description %in% thermo_paths
  ) # Filter for the thermogenic pathways

  # Order with positives first
  pos_nes <- plot.data %>%
    filter(NES >= 0) %>%
    arrange(p.adjust)
  neg_nes <- plot.data %>%
    filter(NES < 0) %>%
    arrange(desc(p.adjust))

  plot.data <- bind_rows(pos_nes, neg_nes)

  # Calculate min and max for -log10(p.adjust)
  min_neg_log_padj <- min(-log10(plot.data$p.adjust))
  max_neg_log_padj <- max(-log10(plot.data$p.adjust))

  # Create plot ordered by NES
  g <- ggplot(plot.data, aes(Tissue, Description)) +
    geom_count(aes(size = -log10(p.adjust), fill = NES), shape = 21, color = "black", stroke = 0.5) +
      # Add asterisks for p.adjust < 0.05
  geom_text(
    data = plot.data %>% filter(p.adjust < 0.05),
    aes(label = "*"),
    color = "black",
    size = 6,
    vjust = 0.5,
    hjust = 1.75
  ) + # Adjust the position of the asterisk
    scale_y_discrete(labels = function(x) wrap_text(x, width = 10)) +
    scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
    scale_y_discrete(limits = rev(unique(plot.data$Description))) +
    theme(
      axis.text.x = element_text(angle = 0, hjust = 0.5, size = 14), # Increase x-axis text size
      axis.text.y = element_text(size = 14), # Increase y-axis text size
      axis.title.x = element_blank(), # Remove x-axis title
      axis.title.y = element_blank(), # Remove y-axis title
      plot.title = element_text(size = 16, face = "bold"), # Increase title size and make it bold
      legend.text = element_text(size = 12), # Increase legend text size
      legend.title = element_text(size = 14) # Increase legend title size
    ) +
    labs(title = paste0(covar, "\n", "Thermogenesis-related pathways"))
  
  ggsave(
    filename = file.path("../output/5_6 - Figures and Analysis/figures",  paste0(date_prefix, "_","Figure_", fig_number[covar], "B_",  covar, "_thermogenic_pathways.png")),
    plot = g, device = "png", width = w, height = h, units = "in", dpi = 600, create.dir = T
  )
  
    ggsave(
    filename = file.path("../output/5_6 - Figures and Analysis/figures",  paste0(date_prefix, "_","Figure_", fig_number[covar], "B_",  covar, "_thermogenic_pathways.tiff")),
    plot = g, device = "tiff", width = w, height = h, units = "in", dpi = 600, create.dir = T
  )
  
  pdf(file.path("../output/5_6 - Figures and Analysis/figures",  paste0(date_prefix, "_","Figure_", fig_number[covar], "B_",  covar, "_thermogenic_pathways.pdf")), width = w, height = h)
  # Print plot to PDF
  print(g)

# Close the PDF device
  dev.off()
}
```


